development:
  adapter: postgresql
  database: heroku_app_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: heroku_app_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: heroku_app_production
  pool: 5
  timeout: 5000
